import os
import sys
import subprocess

# Ensure reportlab is installed
try:
    import reportlab
except ImportError:
    print("reportlab not found. Installing...")
    subprocess.run([sys.executable, "-m", "pip", "install", "reportlab"], check=True)
    import reportlab

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Preformatted
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors

def wrap_text(text, max_len=85):
    lines = []
    for line in text.split('\n'):
        if len(line) <= max_len:
            lines.append(line)
        else:
            # Wrap the long line
            temp_line = line
            while len(temp_line) > max_len:
                # Find the last space before max_len to wrap nicely, if possible
                break_idx = temp_line.rfind(' ', 0, max_len)
                if break_idx == -1 or break_idx < max_len // 2:
                    # No good space, just hard break
                    break_idx = max_len
                lines.append(temp_line[:break_idx])
                temp_line = "    " + temp_line[break_idx:] # Indent wrapped lines
            lines.append(temp_line)
    return '\n'.join(lines)

def get_code_files(base_dir):
    code_files = []
    
    # Exclude folders
    dirs_to_exclude = {'node_modules', '.git', '.gradle', 'build', 'bin', 'dist', '.idea', '.vscode', '__pycache__'}
    
    for root, dirs, files in os.walk(base_dir):
        # Filter directories in-place to avoid walking down excluded ones
        dirs[:] = [d for d in dirs if d not in dirs_to_exclude]
        
        for file in files:
            ext = os.path.splitext(file)[1].lower()
            filepath = os.path.join(root, file)
            relpath = os.path.relpath(filepath, base_dir)
            
            # Double-check exclusions
            if any(part in dirs_to_exclude for part in relpath.split(os.sep)):
                continue
                
            if ext in ['.tsx', '.ts', '.java', '.properties', '.gradle', '.html', '.css']:
                if file in ['package-lock.json']:
                    continue
                code_files.append((relpath, filepath))
                
    # Sort files alphabetically
    code_files.sort(key=lambda x: x[0])
    return code_files

def add_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.HexColor('#A0AEC0'))
    canvas.drawString(36, 20, "Thomas Project Codebase - 偏頭痛個案照護系統")
    canvas.drawRightString(letter[0] - 36, 20, f"Page {doc.page}")
    canvas.restoreState()

def generate_pdf(base_dir, output_pdf):
    print("Collecting files...")
    code_files = get_code_files(base_dir)
    print(f"Found {len(code_files)} code files.")
    
    doc = SimpleDocTemplate(
        output_pdf,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=45
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=colors.HexColor('#1A365D'),
        alignment=TA_CENTER,
        spaceAfter=20
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#4A5568'),
        alignment=TA_CENTER,
        spaceAfter=30
    )
    
    file_header_style = ParagraphStyle(
        'FileHeader',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#2B6CB0'),
        spaceBefore=15,
        spaceAfter=8,
        keepWithNext=True
    )
    
    code_style = ParagraphStyle(
        'CodeStyle',
        fontName='Courier',
        fontSize=7,
        leading=8.5,
        textColor=colors.HexColor('#2D3748'),
        spaceAfter=10
    )
    
    story = []
    
    # Cover Page
    story.append(Spacer(1, 150))
    story.append(Paragraph("Thomas Project Codebase", title_style))
    story.append(Paragraph("偏頭痛個案照護系統 - 完整原始程式碼", subtitle_style))
    story.append(Paragraph("Generated by Antigravity AI Assistant", subtitle_style))
    story.append(PageBreak())
    
    for relpath, filepath in code_files:
        print(f"Adding {relpath}...")
        
        # Add file header
        story.append(Paragraph(f"📄 File: {relpath}", file_header_style))
        
        # Read file content
        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
        except Exception as e:
            content = f"Error reading file: {str(e)}"
            
        # Wrap long lines so they don't clip
        wrapped_content = wrap_text(content, max_len=90)
        
        # Replace XML/HTML special characters for PDF rendering
        escaped_content = wrapped_content.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        
        story.append(Preformatted(escaped_content, code_style))
        story.append(PageBreak())
        
    print("Building PDF...")
    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
    print("PDF build complete.")

if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_pdf = os.path.join(base_dir, "Thomas_Codebase.pdf")
    generate_pdf(base_dir, output_pdf)
